[package]
name = "bs-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.146"
memmap2 = "0.7.0"

[dependencies.iced-x86]
version = "1.19.0"
features = ["code_asm"]