all:
	make -C lib/memutils all
	make -C stack-dummy all
	make -C shared-mem all
	make -C sphincsplus/ref all

clean:
	make -C lib/memutils clean
	make -C stack-dummy clean
	make -C shared-mem clean
	make -C sphincsplus/ref clean
